minecraft_version=26.3-snapshot-4
fabric_api_version=0.155.2+26.3
minecraft_dependency=~26.3-
fabric_api_dependency=>=0.155.2
jade_dependency=*
version_resource_set=26.3
mod_version=1.2.0-snapshot.4
blockCodecApi=removed
datagenApi=bootstrap
snapshot4Api=true
